# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-26 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pubDate',
            field=models.DateTimeField(default='2019-01-26'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='HI', max_length=255),
            preserve_default=False,
        ),
    ]
