# Test against this version of Node.js
environment:
  matrix:
  - nodejs_version: "10"

  # Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  # Output useful info for debugging
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build
build: off
